import React from "react"
import { observer } from "mobx-react"
import { ArticleBox } from "../article-box/ArticleBox"
import s from "./ArticlesContainer.module.scss"

export const ArticlesContainer = observer(() => {

  return (
    <div className={s.container}>
      <ArticleBox articleId={"aa"} articleType={'personal'} bgImage={'https://www.rainforest-alliance.org/wp-content/uploads/2021/06/capybara-square-1.jpg.optimal.jpg'} label={'Jak programownie zniszczyło mi życie'} description={'description'} />
      <ArticleBox articleId={"bb"} articleType={'public'} bgImage={'https://as1.ftcdn.net/v2/jpg/00/41/00/74/1000_F_41007472_jqSWMkZU3b6XpwuHaVXsnp4DZETNylwX.jpg'} label={'Jak programownie zniszczyło mi życie'} description={'description description description description'} />
      <ArticleBox articleId={"cc"} articleType={'personal'} bgImage={'https://as2.ftcdn.net/v2/jpg/00/47/05/35/1000_F_47053566_yFSjxkmllZ7xxZGxcg0u2HE4lGLGBqoz.jpg'} label={'three one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one on one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one onee'} description={'descriptiondescription description description descriptiondescription description description descriptiondescription description description descriptiondescription description description descriptiondescription description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description'} />
      <ArticleBox articleId={"dd"} articleType={'public'} bgImage={'https://i.natgeofe.com/n/566ed88f-7ee4-4a57-be2e-aa312a5f65a1/capybara.jpg'} label={'four'} description={'description'} />
      <ArticleBox articleId={"aa"} articleType={'personal'} bgImage={'https://img.freepik.com/premium-photo/cute-capybara-farm-is-eating_361141-840.jpg'} label={'one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one'} description={'description'} />
      <ArticleBox articleId={"bb"} articleType={'public'} bgImage={'https://static.educalingo.com/img/en/800/capybara.jpg'} label={'two'} description={'description description description description'} />
      <ArticleBox articleId={"cc"} articleType={'personal'} bgImage={'https://st4.depositphotos.com/17973624/27136/i/450/depositphotos_271361008-stock-photo-a-solo-capybara-swimming.jpg'} label={'three one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one on one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one onee'} description={'descriptiondescription description description descriptiondescription description description descriptiondescription description description descriptiondescription description description descriptiondescription description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description'} />
      <ArticleBox articleId={"dd"} articleType={'public'} bgImage={'https://www.tastingtable.com/img/gallery/why-capybara-was-once-considered-a-fish/l-intro-1662056291.jpg'} label={'four'} description={'description'} />
      <ArticleBox articleId={"aa"} articleType={'personal'} bgImage={'https://i.ytimg.com/vi/gFzqB6u-WFc/maxresdefault.jpg'} label={'one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one'} description={'description'} />
      <ArticleBox articleId={"bb"} articleType={'public'} bgImage={'https://img.freepik.com/free-vector/capybara-with-bird-cartoon-style_1308-94127.jpg'} label={'two'} description={'description description description description'} />
      <ArticleBox articleId={"cc"} articleType={'personal'} bgImage={'https://cdna.artstation.com/p/assets/images/images/002/712/226/large/anton-osipkov-capybara-1.jpg'} label={'three one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one on one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one onee'} description={'descriptiondescription description description descriptiondescription description description descriptiondescription description description descriptiondescription description description descriptiondescription description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description'} />
      <ArticleBox articleId={"dd"} articleType={'public'} bgImage={'https://cdn.pixabay.com/photo/2019/06/05/21/02/capybara-4254528__480.jpg'} label={'four'} description={'description'} />
      <ArticleBox articleId={"aa"} articleType={'personal'} bgImage={'https://media.wired.com/photos/5926ad99f3e2356fd800a15d/master/pass/GettyImages-460739682.jpg'} label={'one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one'} description={'description'} />
      <ArticleBox articleId={"bb"} articleType={'public'} bgImage={'https://cdn.shopify.com/s/files/1/0160/2840/1712/products/capybara-plush_photo_square_nh_capybara_04-qtoa.png'} label={'two'} description={'description description description description'} />
      <ArticleBox articleId={"cc"} articleType={'personal'} bgImage={'https://static.wikia.nocookie.net/naturerules1/images/b/b4/Capybara_nationalgeographic_1518115_2.ngsversion.1538507728041.adapt.1900.1.jpg'} label={'three one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one on one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one onee'} description={'descriptiondescription description description descriptiondescription description description descriptiondescription description description descriptiondescription description description descriptiondescription description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description'} />
      <ArticleBox articleId={"dd"} articleType={'public'} bgImage={'https://www.rainforest-alliance.org/wp-content/uploads/2021/06/capybara-square-1.jpg.optimal.jpg'} label={'four'} description={'description'} />
      <ArticleBox articleId={"aa"} articleType={'personal'} bgImage={'https://www.rainforest-alliance.org/wp-content/uploads/2021/06/capybara-square-1.jpg.optimal.jpg'} label={'one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one'} description={'description'} />
      <ArticleBox articleId={"bb"} articleType={'public'} bgImage={'https://www.rainforest-alliance.org/wp-content/uploads/2021/06/capybara-square-1.jpg.optimal.jpg'} label={'two'} description={'description description description description'} />
      <ArticleBox articleId={"cc"} articleType={'personal'} bgImage={'https://www.rainforest-alliance.org/wp-content/uploads/2021/06/capybara-square-1.jpg.optimal.jpg'} label={'three one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one on one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one onee'} description={'descriptiondescription description description descriptiondescription description description descriptiondescription description description descriptiondescription description description descriptiondescription description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description'} />
      <ArticleBox articleId={"dd"} articleType={'public'} bgImage={'https://www.rainforest-alliance.org/wp-content/uploads/2021/06/capybara-square-1.jpg.optimal.jpg'} label={'four'} description={'description'} />
      <ArticleBox articleId={"aa"} articleType={'personal'} bgImage={'https://www.rainforest-alliance.org/wp-content/uploads/2021/06/capybara-square-1.jpg.optimal.jpg'} label={'one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one'} description={'description'} />
      <ArticleBox articleId={"bb"} articleType={'public'} bgImage={'https://www.rainforest-alliance.org/wp-content/uploads/2021/06/capybara-square-1.jpg.optimal.jpg'} label={'two'} description={'description description description description'} />
      <ArticleBox articleId={"cc"} articleType={'personal'} bgImage={'https://www.rainforest-alliance.org/wp-content/uploads/2021/06/capybara-square-1.jpg.optimal.jpg'} label={'three one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one on one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one one onee'} description={'descriptiondescription description description descriptiondescription description description descriptiondescription description description descriptiondescription description description descriptiondescription description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description description'} />
      <ArticleBox articleId={"dd"} articleType={'public'} bgImage={'https://www.rainforest-alliance.org/wp-content/uploads/2021/06/capybara-square-1.jpg.optimal.jpg'} label={'four'} description={'description'} />
    </div>
  )
})
